# Generated by Django 5.1.4 on 2024-12-24 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loanamountapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdetails",
            name="age",
            field=models.PositiveIntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(69),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="home_value",
            field=models.FloatField(
                blank=True,
                default=571429,
                validators=[
                    django.core.validators.MinValueValidator(571429),
                    django.core.validators.MaxValueValidator(14500000),
                ],
            ),
        ),
    ]
